name: Check

on:
  schedule:
    - cron: "0 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Java
        run: |
          sudo apt update 
          sudo apt install default-jre
          
      - name: Configure
        run: |
          cd recurring-execution-with-actions
          echo "{ :min_score 600 :chat \"${{ secrets.TELEGRAM_CHAT }}\" :bot_token \"${{ secrets.TELEGRAM_BOT_TOKEN }}\" :run_every_miliseconds 3600000 }" > config.edn
          
      - name: Run
        run: |
          cd recurring-execution-with-actions
          java -jar isahn-1.0.1-standalone.jar
          
      - name: Update database
        run: |
          cd recurring-execution-with-actions
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add isahn_history.json
          git commit -m 'Update history'
          git push -f origin master
